/* eslint-disable no-restricted-globals */
/* eslint-disable no-undef */

import { clientsClaim } from 'workbox-core';
import { precacheAndRoute } from 'workbox-precaching';

// on install skip waiting to immediately activate the service worker
self.addEventListener('install', (event) => {
  event.waitUntil(self.skipWaiting());
});

// take control of the client if not already controlled by the service worker
clientsClaim();

// precache assets generated by webpack
precacheAndRoute(self.__WB_MANIFEST);
